name: "My Action"
description: "Test my action"

inputs:
  message: 
    description: mensaje
    required: true
    default: "Sin Mensaje"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo
      run: echo "${{ inputs.message }}"
      shell: bash