name: Test Composite Action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    steps:
    - name: ls
      uses: ./.github/actions/my-action
    